# Generated by Django 3.0.5 on 2020-04-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_full_name', models.CharField(max_length=150)),
                ('author_id', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
    ]
