# Generated by Django 3.0.5 on 2020-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='author_full_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
