# Generated by Django 3.0.5 on 2020-04-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20200430_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
