# Generated by Django 3.0.5 on 2020-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20200430_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profession',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
